language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: EmbeddingIntentClassifier
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    dimensions: ["time", "duration","number"]
    timezone: "Etc/GMT+1"


policies:
  - name: MemoizationPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: "utter_unclear"
  - name: KerasPolicy
  - name: FormPolicy
  - name: MappingPolicy